[workspace]
members = ["license-store-cache"]

[workspace.package]
version = "0.1.1"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
askalono = "0.4.6"

[package]
name = "nix-init"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Generate Nix packages from URLs with hash prefetching, dependency inference, license detection, and more"
readme = "README.md"
homepage = "https://github.com/nix-community/nix-init"
repository = "https://github.com/nix-community/nix-init"
license.workspace = true
keywords = ["cli", "interactive", "generate", "nix", "package"]
categories = ["command-line-utilities"]
include = ["data", "src", "Cargo.lock", "Cargo.toml", "build.rs"]

[dependencies]
anyhow = "1.0.69"
askalono.workspace = true
bstr = "1.2.0"
cargo = "0.69.0"
chumsky = "1.0.0-alpha.3"
expand = "0.2.1"
flate2 = "1.0.25"
heck = "0.4.1"
indoc = "2.0.1"
is-terminal = "0.4.4"
itertools = "0.10.5"
once_cell = "1.17.1"
owo-colors = "3.5.0"
parse-display = "0.8.0"
paste = "1.0.12"
pep-508 = "0.3.0"
rayon = "1.6.1"
regex = "1.7.1"
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
rustc-hash = "1.1.0"
secrecy = { version = "0.8.0", features = ["serde"] }
semver = "1.0.16"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.3.0"
serde_yaml = "0.9.19"
shlex = "1.1.0"
spdx = "0.10.0"
tar = "0.4.38"
tempfile = "3.4.0"
time = { version = "0.3.20", features = ["parsing", "serde"] }
toml = { version = "0.7.2", default-features = false, features = ["parse"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
xdg = "2.4.1"
zip = "0.6.4"

[dependencies.clap]
version = "4.1.8"
features = ["cargo", "derive", "unicode", "wrap_help"]

[dependencies.rustyline]
version = "11.0.0"
default-features = false
features = ["derive", "with-fuzzy"]

[dependencies.tokio]
version = "1.26.0"
features = ["macros", "process", "rt-multi-thread"]

[build-dependencies]
clap = { version = "4.1.8", features = ["derive"] }
clap_complete = "4.1.4"
clap_mangen = "0.2.9"

[features]
default = ["vendored", "reqwest/rustls-tls"]
vendored = ["cargo/vendored-libgit2", "cargo/vendored-openssl"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
