[workspace]
members = ["license-store-cache"]

[workspace.package]
version = "0.2.4"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
askalono = "0.4.6"

[package]
name = "nix-init"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Generate Nix packages from URLs with hash prefetching, dependency inference, license detection, and more"
readme = "README.md"
homepage = "https://github.com/nix-community/nix-init"
repository = "https://github.com/nix-community/nix-init"
license.workspace = true
keywords = ["cli", "interactive", "generate", "nix", "package"]
categories = ["command-line-utilities"]
include = ["data", "src", "Cargo.lock", "Cargo.toml", "build.rs"]

[dependencies]
anyhow = "1.0.72"
askalono.workspace = true
bstr = "1.6.0"
cargo = "0.72.1"
chumsky = "1.0.0-alpha.4"
expand = "0.3.0"
flate2 = "1.0.26"
heck = "0.4.1"
indoc = "2.0.3"
is-terminal = "0.4.9"
itertools = "0.11.0"
once_cell = "1.18.0"
owo-colors = "3.5.0"
parse-display = "0.8.2"
pep-508 = "0.3.0"
rayon = "1.7.0"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
rustc-hash = "1.1.0"
secrecy = { version = "0.8.0", features = ["serde"] }
semver = "1.0.18"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
serde_with = "3.1.0"
serde_yaml = "0.9.25"
shlex = "1.1.0"
spdx = "0.10.2"
tar = "0.4.39"
tempfile = "3.7.0"
time = { version = "0.3.23", features = ["parsing", "serde"] }
toml = { version = "0.7.6", default-features = false, features = ["parse"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.4.0"
xdg = "2.5.2"
zip = "0.6.6"

[dependencies.clap]
version = "4.3.17"
features = ["cargo", "derive", "unicode", "wrap_help"]

[dependencies.rustyline]
version = "12.0.0"
default-features = false
features = ["derive", "with-fuzzy"]

[dependencies.tokio]
version = "1.29.1"
features = ["macros", "process", "rt-multi-thread"]

[build-dependencies]
clap = { version = "4.3.17", features = ["derive"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.12"

[dev-dependencies]
heck = "0.4.1"
insta = "1.31.0"
tempfile = "3.7.0"

[features]
default = ["vendored"]
vendored = ["cargo/vendored-libgit2", "cargo/vendored-openssl"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
