[workspace]
members = ["license-store-cache"]

[workspace.package]
version = "0.2.3"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
license = "MPL-2.0"

[workspace.dependencies]
askalono = "0.4.6"

[package]
name = "nix-init"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Generate Nix packages from URLs with hash prefetching, dependency inference, license detection, and more"
readme = "README.md"
homepage = "https://github.com/nix-community/nix-init"
repository = "https://github.com/nix-community/nix-init"
license.workspace = true
keywords = ["cli", "interactive", "generate", "nix", "package"]
categories = ["command-line-utilities"]
include = ["data", "src", "Cargo.lock", "Cargo.toml", "build.rs"]

[dependencies]
anyhow = "1.0.71"
askalono.workspace = true
bstr = "1.5.0"
cargo = "0.70.1"
chumsky = "1.0.0-alpha.4"
expand = "0.3.0"
flate2 = "1.0.25"
heck = "0.4.1"
indoc = "2.0.1"
is-terminal = "0.4.7"
itertools = "0.10.5"
once_cell = "1.17.2"
owo-colors = "3.5.0"
parse-display = "0.8.0"
pep-508 = "0.3.0"
rayon = "1.7.0"
regex = "1.8.3"
reqwest = { version = "0.11.18", features = ["json"] }
rustc-hash = "1.1.0"
secrecy = { version = "0.8.0", features = ["serde"] }
semver = "1.0.17"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "3.0.0"
serde_yaml = "0.9.21"
shlex = "1.1.0"
spdx = "0.10.1"
tar = "0.4.38"
tempfile = "3.5.0"
time = { version = "0.3.21", features = ["parsing", "serde"] }
toml = { version = "0.7.4", default-features = false, features = ["parse"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.3.1"
xdg = "2.5.0"
zip = "0.6.6"

[dependencies.clap]
version = "4.3.0"
features = ["cargo", "derive", "unicode", "wrap_help"]

[dependencies.rustyline]
version = "11.0.0"
default-features = false
features = ["derive", "with-fuzzy"]

[dependencies.tokio]
version = "1.28.2"
features = ["macros", "process", "rt-multi-thread"]

[build-dependencies]
clap = { version = "4.3.0", features = ["derive"] }
clap_complete = "4.3.0"
clap_mangen = "0.2.11"

[dev-dependencies]
heck = "0.4.1"
insta = "1.29.0"
tempfile = "3.5.0"

[features]
default = ["vendored"]
vendored = ["cargo/vendored-libgit2", "cargo/vendored-openssl"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
